# Generated by Django 6.0.1 on 2026-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
    ]
